name: Deploy to Preview Channel

on:
  - pull_request
  - push
  
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.2f5997aa5e8c68706820200548a198a3a7ca9f78 }}"
          firebaseServiceAccount: "${{ secrets.github-action }}"
          expires: 30d
          projectId: musikmedia-epizy

